remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: SF Lindy Society
description: We are the official page for SF Lindy Society at DecoDance Bar on Polk st!